### ISSUE TITLE
Die drei ??? Telegram Bot Offline?

### ISSUE THREAD

**Issue by KerstinMaur** [Simsso/Die-drei-Fragezeichen-Telegram-bot#1]
Hi, is the bot offline? I do not get a reply from it. 🤔
It would be awesome if you could check it as the bot looks really helpful from the screenshots in the Readme. 😎

**Comment by Simsso** [comment]
Hi Kerstin, yes, the bot is not being hosted right now. I don't know about your background, but if you're interested feel free to take a look and try to host it. I am not sure about why I took it down, I believe there was an occasional problem with Spotify changing track IDs and that triggered the bot to send out hundreds of updates to each user (which was not cool).

**Comment by Simsso** [comment]
Update: In a flash of energy (_"In einem Anflug von Tatendrang"_) I restarted the application now. Maybe the problem resolved itself on Spotify's side. In any case, `/random` should now work and we can again let it pick episodes for us to listen to 😊.

**Comment by KerstinMaur** [comment]
Thanks, that are awesome news! 👍

**Comment by Simsso** [comment]
Coincidentally, a new episode got released this morning. The alerting seems to work fine, so I'll close this issue and listen to the new episode soon 😃!

![image](https://user-images.githubusercontent.com/6556307/82027938-3adbd380-9695-11ea-9039-eea8157bf3c5.png)

**Comment by KerstinMaur** [comment]
It is working great here too. 😊
Thank you so much!

**Comment by ClassyCodingClara** [comment]
May it be that the bot is offline again, @Simsso & @KerstinMaur? 🤔

**Comment by KerstinMaur** [comment]
> May it be that the bot is offline again, @Simsso & @KerstinMaur? 🤔

Yes, I think so. 😔

**Comment by MaryseLegnochiaro** [comment]
Same here 😱
